server:
  port: 12000
elasticsearch:
  host: 192.168.56.10
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis

#logging:
#  level:
#    com.atguigu.gulimall.search: debug
#    root: warn
#  pattern:
#    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

