server:
  port: 8080
elasticsearch:
  host: elasticsearch.gulimall
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.gulimall:8848
  redis:
    host: redis.gulimall
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis

#logging:
#  level:
#    com.atguigu.gulimall.search: debug
#    root: warn
#  pattern:
#    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"

